### ISSUE TITLE
Exits successfully, even after errors

### ISSUE THREAD

**Issue by kseistrup** [social4git/social4git#12]
My `social4git` has `stopped` showing posts. At all. Even posts it showed yesterday are no longer shewn. Since `social4git` exits with `EXIT_SUCCESS` (i.e., 0 on a Linux system), I didn't believe this to be an error. Instead I imagined that perhaps it would default to not show posts that are older than a couple of days.

However, when I ran it with `--verbose`, this is what I saw:

```txt
2023-04-01T15:24:53.796+0200	INFO	base/logging.go:61	github.com/gov4git/lib4git@v0.0.9/git/nocache.go:36 materializing repo https://codeberg.org/kas/kas.social4git.private.git on disk /tmp/user/1234/nonce-n5qngltsmzjc

open /tmp/user/1234/nonce-n5qngltsmzjc/post/2023/04/01: no such file or directory
goroutine 1 [running]:
```

It is true that the last two directories (`…/04/01/`) don't exist. There are some directories for March, though the posts are never shewn before `social4git` exits “successfully”.

And after this error, the “nonce” directory is never cleaned up. Instead it is just left to rot on the filesystem.

----

Version: latest (0.0.5, I believe)
Go version: go1.20.2 linux/amd64
OS: Linux x86_64

**Comment by kseistrup** [comment]
PS: When omitting `--verbose`, no stacktrace is shewn, and no “nonce” directory structure is left behind.

**Comment by petar** [comment]
I fixed this bug and it was also the source of some of the confusion you ran into in https://github.com/social4git/social4git/issues/13
