### ISSUE TITLE
How does “show --date” work?

### ISSUE THREAD

**Issue by kseistrup** [social4git/social4git#13]
`social4git show --help` says:

```
Flags:
      --date string   show posts from a UTC date in format MM/DD/YYYY
```

Does “from a UTC date” mean posts posted on that UTC date (from 00:00:00 to 23:59:59.999999 UTC)?

When I run `social4git show --date 03/31/2023` I see posts ranging from 2023-03-24 to 2023-03-30, but none from yesterday, so I wonder if I take “from a UTC date” to mean something it doesn't (English is not my first language).

`show --month` and `show --year` don't show a thing (see #12).

----

Related: The `MM/DD/YYYY` date format is a US peculiarity. Can we have ISO-8601 dates (YYYY-MM-DD), too? Please.

**Comment by petar** [comment]
The help screen is missing adequate doc. The show command needs two pieces of information: window duration (day, month, year) and a date inside the window. The command always shows tweets within the calendar day/month/year containing the given date.

The duration is specified with --day --month --year, defaulting to month.
The date is specified with --date, defaulting to today.

All dates are UTC-only currently (hopefully this changes https://github.com/social4git/social4git/issues/14)
Date formats are US-only currently (welcoming contributions https://github.com/social4git/social4git/issues/15)
